version: '3'

networks:
  backend:

services:

  doc-emb:
    build: .
    command: python doc_emb/embed.py
    environment:
      - PORT=5000
      - MODEL_PATH=/app/models/torontobooks_unigrams.bin
    networks:
      - backend
    volumes:
      - ./models:/app/models